spring.application.name=cart-service
# Server
server.port=8083

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT - MUST be same secret as auth-service!
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000


# Actuator
management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
app.gateway-url=${GATEWAY_URL}
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Cache
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Jackson date serialization
spring.jackson.serialization.write-dates-as-timestamps=false

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true